#############################################################################
# Makefile for building: OneFM
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  OneFM.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile OneFM.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -pthread -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -pthread -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libxml2 -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -pthread -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lxml2 -lglib-2.0 -lQt5Widgets -L/usr/lib/x86_64-linux-gnu -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		currentsong.cpp \
		gstreamerradio.cpp qrc_images.cpp \
		moc_mainwindow.cpp \
		moc_currentsong.cpp \
		moc_radio.cpp \
		moc_gstreamerradio.cpp
OBJECTS       = main.o \
		mainwindow.o \
		currentsong.o \
		gstreamerradio.o \
		qrc_images.o \
		moc_mainwindow.o \
		moc_currentsong.o \
		moc_radio.o \
		moc_gstreamerradio.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		OneFM.pro \
		images.qrc \
		OneFM.pro
QMAKE_TARGET  = OneFM
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = OneFM


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OneFM.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		OneFM.pro \
		images.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl
	$(QMAKE) -o Makefile OneFM.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
OneFM.pro:
images.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile OneFM.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/OneFM1.0.0 || mkdir -p .tmp/OneFM1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/OneFM1.0.0/ && $(COPY_FILE) --parents images.qrc .tmp/OneFM1.0.0/ && $(COPY_FILE) --parents mainwindow.h currentsong.h radio.h gstreamerradio.h .tmp/OneFM1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp currentsong.cpp gstreamerradio.cpp .tmp/OneFM1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/OneFM1.0.0/ && (cd `dirname .tmp/OneFM1.0.0` && $(TAR) OneFM1.0.0.tar OneFM1.0.0 && $(COMPRESS) OneFM1.0.0.tar) && $(MOVE) `dirname .tmp/OneFM1.0.0`/OneFM1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/OneFM1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		images/checkbox_checked.png \
		images/center-bg.png \
		images/close-icon.png \
		images/minimize-icon.png \
		images/hand.png \
		images/minimize-icon-hover.png \
		images/close-icon-hover.png \
		images/volume-icon-up.png \
		images/tux.png \
		images/volume-controller-pressed.png \
		images/background.png \
		images/menu-bg.png \
		images/onefmro.png \
		images/stop.png \
		images/volume-controller.png \
		images/play-button.png \
		images/volume-grid.png \
		images/hearth.png \
		images/acum-live.png \
		images/star.png \
		images/menu-icon.png \
		images/logo-0.png \
		images/volume-icon-down.png \
		images/logo-small-0.png \
		images/logo-1.png \
		images/change-radio.png \
		images/logo-small-1.png \
		images/checkbox_unchecked.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_currentsong.cpp moc_radio.cpp moc_gstreamerradio.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_currentsong.cpp moc_radio.cpp moc_gstreamerradio.cpp
moc_mainwindow.cpp: /usr/include/qt5/QtWidgets/QMainWindow \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtWidgets/QLabel \
		/usr/include/qt5/QtWidgets/qlabel.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtCore/QSettings \
		/usr/include/qt5/QtCore/qsettings.h \
		/usr/include/qt5/QtCore/QPropertyAnimation \
		/usr/include/qt5/QtCore/qpropertyanimation.h \
		/usr/include/qt5/QtCore/qvariantanimation.h \
		/usr/include/qt5/QtCore/qeasingcurve.h \
		/usr/include/qt5/QtCore/qabstractanimation.h \
		/usr/include/qt5/QtCore/QUrl \
		/usr/include/qt5/QtWidgets/QGraphicsOpacityEffect \
		/usr/include/qt5/QtWidgets/qgraphicseffect.h \
		/usr/include/qt5/QtGui/QDesktopServices \
		/usr/include/qt5/QtGui/qdesktopservices.h \
		/usr/include/qt5/QtCore/qstandardpaths.h \
		/usr/include/qt5/QtGui/QMouseEvent \
		/usr/include/qt5/QtWidgets/QApplication \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h \
		/usr/include/qt5/QtCore/QObject \
		currentsong.h \
		/usr/include/qt5/QtCore/QString \
		/usr/include/qt5/QtCore/QTimer \
		/usr/include/qt5/QtCore/qtimer.h \
		/usr/include/qt5/QtCore/qbasictimer.h \
		/usr/include/qt5/QtCore/QDebug \
		/usr/include/qt5/QtNetwork/QNetworkReply \
		/usr/include/qt5/QtNetwork/qnetworkreply.h \
		/usr/include/qt5/QtCore/QIODevice \
		/usr/include/qt5/QtCore/QVariant \
		/usr/include/qt5/QtNetwork/QNetworkRequest \
		/usr/include/qt5/QtNetwork/qnetworkrequest.h \
		/usr/include/qt5/QtCore/QSharedDataPointer \
		/usr/include/qt5/QtNetwork/QNetworkAccessManager \
		/usr/include/qt5/QtNetwork/qnetworkaccessmanager.h \
		/usr/include/qt5/QtNetwork/QSslConfiguration \
		/usr/include/qt5/QtNetwork/qsslconfiguration.h \
		/usr/include/qt5/QtNetwork/qsslsocket.h \
		/usr/include/qt5/QtNetwork/qtcpsocket.h \
		/usr/include/qt5/QtNetwork/qabstractsocket.h \
		/usr/include/qt5/QtNetwork/qsslerror.h \
		/usr/include/qt5/QtNetwork/qsslcertificate.h \
		/usr/include/qt5/QtCore/qcryptographichash.h \
		/usr/include/qt5/QtCore/qdatetime.h \
		/usr/include/qt5/QtNetwork/qssl.h \
		/usr/include/qt5/QtCore/QFlags \
		/usr/include/qt5/QtCore/QEventLoop \
		gstreamerradio.h \
		radio.h \
		/usr/include/gstreamer-0.10/gst/gst.h \
		/usr/include/glib-2.0/glib.h \
		/usr/include/glib-2.0/glib/galloca.h \
		/usr/include/glib-2.0/glib/gtypes.h \
		/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h \
		/usr/include/glib-2.0/glib/gmacros.h \
		/usr/include/glib-2.0/glib/gversionmacros.h \
		/usr/include/glib-2.0/glib/garray.h \
		/usr/include/glib-2.0/glib/gasyncqueue.h \
		/usr/include/glib-2.0/glib/gthread.h \
		/usr/include/glib-2.0/glib/gatomic.h \
		/usr/include/glib-2.0/glib/gerror.h \
		/usr/include/glib-2.0/glib/gquark.h \
		/usr/include/glib-2.0/glib/gbacktrace.h \
		/usr/include/glib-2.0/glib/gbase64.h \
		/usr/include/glib-2.0/glib/gbitlock.h \
		/usr/include/glib-2.0/glib/gbookmarkfile.h \
		/usr/include/glib-2.0/glib/gbytes.h \
		/usr/include/glib-2.0/glib/gcharset.h \
		/usr/include/glib-2.0/glib/gchecksum.h \
		/usr/include/glib-2.0/glib/gconvert.h \
		/usr/include/glib-2.0/glib/gdataset.h \
		/usr/include/glib-2.0/glib/gdate.h \
		/usr/include/glib-2.0/glib/gdatetime.h \
		/usr/include/glib-2.0/glib/gtimezone.h \
		/usr/include/glib-2.0/glib/gdir.h \
		/usr/include/glib-2.0/glib/genviron.h \
		/usr/include/glib-2.0/glib/gfileutils.h \
		/usr/include/glib-2.0/glib/ggettext.h \
		/usr/include/glib-2.0/glib/ghash.h \
		/usr/include/glib-2.0/glib/glist.h \
		/usr/include/glib-2.0/glib/gmem.h \
		/usr/include/glib-2.0/glib/gnode.h \
		/usr/include/glib-2.0/glib/ghmac.h \
		/usr/include/glib-2.0/glib/ghook.h \
		/usr/include/glib-2.0/glib/ghostutils.h \
		/usr/include/glib-2.0/glib/giochannel.h \
		/usr/include/glib-2.0/glib/gmain.h \
		/usr/include/glib-2.0/glib/gpoll.h \
		/usr/include/glib-2.0/glib/gslist.h \
		/usr/include/glib-2.0/glib/gstring.h \
		/usr/include/glib-2.0/glib/gunicode.h \
		/usr/include/glib-2.0/glib/gutils.h \
		/usr/include/glib-2.0/glib/gkeyfile.h \
		/usr/include/glib-2.0/glib/gmappedfile.h \
		/usr/include/glib-2.0/glib/gmarkup.h \
		/usr/include/glib-2.0/glib/gmessages.h \
		/usr/include/glib-2.0/glib/goption.h \
		/usr/include/glib-2.0/glib/gpattern.h \
		/usr/include/glib-2.0/glib/gprimes.h \
		/usr/include/glib-2.0/glib/gqsort.h \
		/usr/include/glib-2.0/glib/gqueue.h \
		/usr/include/glib-2.0/glib/grand.h \
		/usr/include/glib-2.0/glib/gregex.h \
		/usr/include/glib-2.0/glib/gscanner.h \
		/usr/include/glib-2.0/glib/gsequence.h \
		/usr/include/glib-2.0/glib/gshell.h \
		/usr/include/glib-2.0/glib/gslice.h \
		/usr/include/glib-2.0/glib/gspawn.h \
		/usr/include/glib-2.0/glib/gstrfuncs.h \
		/usr/include/glib-2.0/glib/gstringchunk.h \
		/usr/include/glib-2.0/glib/gtestutils.h \
		/usr/include/glib-2.0/glib/gthreadpool.h \
		/usr/include/glib-2.0/glib/gtimer.h \
		/usr/include/glib-2.0/glib/gtrashstack.h \
		/usr/include/glib-2.0/glib/gtree.h \
		/usr/include/glib-2.0/glib/gurifuncs.h \
		/usr/include/glib-2.0/glib/gvarianttype.h \
		/usr/include/glib-2.0/glib/gvariant.h \
		/usr/include/glib-2.0/glib/gversion.h \
		/usr/include/glib-2.0/glib/gwin32.h \
		/usr/include/glib-2.0/glib/deprecated/gallocator.h \
		/usr/include/glib-2.0/glib/deprecated/gcache.h \
		/usr/include/glib-2.0/glib/deprecated/gcompletion.h \
		/usr/include/glib-2.0/glib/deprecated/gmain.h \
		/usr/include/glib-2.0/glib/deprecated/grel.h \
		/usr/include/glib-2.0/glib/deprecated/gthread.h \
		/usr/include/gstreamer-0.10/gst/glib-compat.h \
		/usr/include/gstreamer-0.10/gst/gstenumtypes.h \
		/usr/include/glib-2.0/glib-object.h \
		/usr/include/glib-2.0/gobject/gbinding.h \
		/usr/include/glib-2.0/gobject/gobject.h \
		/usr/include/glib-2.0/gobject/gtype.h \
		/usr/include/glib-2.0/gobject/gvalue.h \
		/usr/include/glib-2.0/gobject/gparam.h \
		/usr/include/glib-2.0/gobject/gclosure.h \
		/usr/include/glib-2.0/gobject/gsignal.h \
		/usr/include/glib-2.0/gobject/gmarshal.h \
		/usr/include/glib-2.0/gobject/gboxed.h \
		/usr/include/glib-2.0/gobject/glib-types.h \
		/usr/include/glib-2.0/gobject/genums.h \
		/usr/include/glib-2.0/gobject/gparamspecs.h \
		/usr/include/glib-2.0/gobject/gsourceclosure.h \
		/usr/include/glib-2.0/gobject/gtypemodule.h \
		/usr/include/glib-2.0/gobject/gtypeplugin.h \
		/usr/include/glib-2.0/gobject/gvaluearray.h \
		/usr/include/glib-2.0/gobject/gvaluetypes.h \
		/usr/include/gstreamer-0.10/gst/gstversion.h \
		/usr/include/gstreamer-0.10/gst/gstatomicqueue.h \
		/usr/include/gstreamer-0.10/gst/gstbin.h \
		/usr/include/gstreamer-0.10/gst/gstelement.h \
		/usr/include/gstreamer-0.10/gst/gstconfig.h \
		/usr/include/libxml2/libxml/parser.h \
		/usr/include/libxml2/libxml/xmlversion.h \
		/usr/include/libxml2/libxml/xmlexports.h \
		/usr/include/libxml2/libxml/tree.h \
		/usr/include/libxml2/libxml/xmlstring.h \
		/usr/include/libxml2/libxml/xmlregexp.h \
		/usr/include/libxml2/libxml/dict.h \
		/usr/include/libxml2/libxml/xmlmemory.h \
		/usr/include/libxml2/libxml/threads.h \
		/usr/include/libxml2/libxml/globals.h \
		/usr/include/libxml2/libxml/xmlerror.h \
		/usr/include/libxml2/libxml/SAX.h \
		/usr/include/libxml2/libxml/xlink.h \
		/usr/include/libxml2/libxml/SAX2.h \
		/usr/include/libxml2/libxml/hash.h \
		/usr/include/libxml2/libxml/valid.h \
		/usr/include/libxml2/libxml/list.h \
		/usr/include/libxml2/libxml/xmlautomata.h \
		/usr/include/libxml2/libxml/entities.h \
		/usr/include/libxml2/libxml/encoding.h \
		/usr/include/libxml2/libxml/xmlIO.h \
		/usr/include/gstreamer-0.10/gst/gstobject.h \
		/usr/include/gstreamer-0.10/gst/gstpad.h \
		/usr/include/gstreamer-0.10/gst/gstbuffer.h \
		/usr/include/gstreamer-0.10/gst/gstminiobject.h \
		/usr/include/gstreamer-0.10/gst/gstclock.h \
		/usr/include/gstreamer-0.10/gst/gstcaps.h \
		/usr/include/gstreamer-0.10/gst/gststructure.h \
		/usr/include/gstreamer-0.10/gst/gstdatetime.h \
		/usr/include/gstreamer-0.10/gst/gstbufferlist.h \
		/usr/include/gstreamer-0.10/gst/gstevent.h \
		/usr/include/gstreamer-0.10/gst/gstformat.h \
		/usr/include/gstreamer-0.10/gst/gstiterator.h \
		/usr/include/gstreamer-0.10/gst/gsttaglist.h \
		/usr/include/gstreamer-0.10/gst/gstquery.h \
		/usr/include/gstreamer-0.10/gst/gsttask.h \
		/usr/include/gstreamer-0.10/gst/gsttaskpool.h \
		/usr/include/gstreamer-0.10/gst/gstpadtemplate.h \
		/usr/include/gstreamer-0.10/gst/gstbus.h \
		/usr/include/gstreamer-0.10/gst/gstmessage.h \
		/usr/include/gstreamer-0.10/gst/gstelementfactory.h \
		/usr/include/gstreamer-0.10/gst/gstplugin.h \
		/usr/include/glib-2.0/gmodule.h \
		/usr/include/gstreamer-0.10/gst/gstmacros.h \
		/usr/include/gstreamer-0.10/gst/gstpluginfeature.h \
		/usr/include/gstreamer-0.10/gst/gstindex.h \
		/usr/include/gstreamer-0.10/gst/gstindexfactory.h \
		/usr/include/gstreamer-0.10/gst/gstchildproxy.h \
		/usr/include/gstreamer-0.10/gst/gstdebugutils.h \
		/usr/include/gstreamer-0.10/gst/gsterror.h \
		/usr/include/gstreamer-0.10/gst/gstghostpad.h \
		/usr/include/gstreamer-0.10/gst/gstinfo.h \
		/usr/include/gstreamer-0.10/gst/gstinterface.h \
		/usr/include/gstreamer-0.10/gst/gstmarshal.h \
		/usr/include/gstreamer-0.10/gst/gstparamspecs.h \
		/usr/include/gstreamer-0.10/gst/gstvalue.h \
		/usr/include/gstreamer-0.10/gst/gstpipeline.h \
		/usr/include/gstreamer-0.10/gst/gstpoll.h \
		/usr/include/gstreamer-0.10/gst/gstpreset.h \
		/usr/include/gstreamer-0.10/gst/gstregistry.h \
		/usr/include/gstreamer-0.10/gst/gstsegment.h \
		/usr/include/gstreamer-0.10/gst/gstsystemclock.h \
		/usr/include/gstreamer-0.10/gst/gsttagsetter.h \
		/usr/include/gstreamer-0.10/gst/gsttrace.h \
		/usr/include/gstreamer-0.10/gst/gsttypefind.h \
		/usr/include/gstreamer-0.10/gst/gsttypefindfactory.h \
		/usr/include/gstreamer-0.10/gst/gsturi.h \
		/usr/include/gstreamer-0.10/gst/gstutils.h \
		/usr/include/gstreamer-0.10/gst/gstparse.h \
		/usr/include/gstreamer-0.10/gst/gstxml.h \
		/usr/include/gstreamer-0.10/gst/gstcompat.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_currentsong.cpp: /usr/include/qt5/QtCore/QString \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/QUrl \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtCore/QTimer \
		/usr/include/qt5/QtCore/qtimer.h \
		/usr/include/qt5/QtCore/qbasictimer.h \
		/usr/include/qt5/QtCore/QDebug \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtNetwork/QNetworkReply \
		/usr/include/qt5/QtNetwork/qnetworkreply.h \
		/usr/include/qt5/QtCore/QIODevice \
		/usr/include/qt5/QtCore/QVariant \
		/usr/include/qt5/QtNetwork/QNetworkRequest \
		/usr/include/qt5/QtNetwork/qnetworkrequest.h \
		/usr/include/qt5/QtCore/QSharedDataPointer \
		/usr/include/qt5/QtNetwork/QNetworkAccessManager \
		/usr/include/qt5/QtNetwork/qnetworkaccessmanager.h \
		/usr/include/qt5/QtCore/QObject \
		/usr/include/qt5/QtNetwork/QSslConfiguration \
		/usr/include/qt5/QtNetwork/qsslconfiguration.h \
		/usr/include/qt5/QtNetwork/qsslsocket.h \
		/usr/include/qt5/QtNetwork/qtcpsocket.h \
		/usr/include/qt5/QtNetwork/qabstractsocket.h \
		/usr/include/qt5/QtNetwork/qsslerror.h \
		/usr/include/qt5/QtNetwork/qsslcertificate.h \
		/usr/include/qt5/QtCore/qcryptographichash.h \
		/usr/include/qt5/QtCore/qdatetime.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtNetwork/qssl.h \
		/usr/include/qt5/QtCore/QFlags \
		/usr/include/qt5/QtCore/QEventLoop \
		/usr/include/qt5/QtCore/qeventloop.h \
		currentsong.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include currentsong.h -o moc_currentsong.cpp

moc_radio.cpp: /usr/include/qt5/QtCore/QObject \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/QString \
		/usr/include/qt5/QtCore/QDebug \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		radio.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include radio.h -o moc_radio.cpp

moc_gstreamerradio.cpp: /usr/include/qt5/QtCore/QDebug \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		radio.h \
		/usr/include/qt5/QtCore/QObject \
		/usr/include/qt5/QtCore/QString \
		/usr/include/gstreamer-0.10/gst/gst.h \
		/usr/include/glib-2.0/glib.h \
		/usr/include/glib-2.0/glib/galloca.h \
		/usr/include/glib-2.0/glib/gtypes.h \
		/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h \
		/usr/include/glib-2.0/glib/gmacros.h \
		/usr/include/glib-2.0/glib/gversionmacros.h \
		/usr/include/glib-2.0/glib/garray.h \
		/usr/include/glib-2.0/glib/gasyncqueue.h \
		/usr/include/glib-2.0/glib/gthread.h \
		/usr/include/glib-2.0/glib/gatomic.h \
		/usr/include/glib-2.0/glib/gerror.h \
		/usr/include/glib-2.0/glib/gquark.h \
		/usr/include/glib-2.0/glib/gbacktrace.h \
		/usr/include/glib-2.0/glib/gbase64.h \
		/usr/include/glib-2.0/glib/gbitlock.h \
		/usr/include/glib-2.0/glib/gbookmarkfile.h \
		/usr/include/glib-2.0/glib/gbytes.h \
		/usr/include/glib-2.0/glib/gcharset.h \
		/usr/include/glib-2.0/glib/gchecksum.h \
		/usr/include/glib-2.0/glib/gconvert.h \
		/usr/include/glib-2.0/glib/gdataset.h \
		/usr/include/glib-2.0/glib/gdate.h \
		/usr/include/glib-2.0/glib/gdatetime.h \
		/usr/include/glib-2.0/glib/gtimezone.h \
		/usr/include/glib-2.0/glib/gdir.h \
		/usr/include/glib-2.0/glib/genviron.h \
		/usr/include/glib-2.0/glib/gfileutils.h \
		/usr/include/glib-2.0/glib/ggettext.h \
		/usr/include/glib-2.0/glib/ghash.h \
		/usr/include/glib-2.0/glib/glist.h \
		/usr/include/glib-2.0/glib/gmem.h \
		/usr/include/glib-2.0/glib/gnode.h \
		/usr/include/glib-2.0/glib/ghmac.h \
		/usr/include/glib-2.0/glib/ghook.h \
		/usr/include/glib-2.0/glib/ghostutils.h \
		/usr/include/glib-2.0/glib/giochannel.h \
		/usr/include/glib-2.0/glib/gmain.h \
		/usr/include/glib-2.0/glib/gpoll.h \
		/usr/include/glib-2.0/glib/gslist.h \
		/usr/include/glib-2.0/glib/gstring.h \
		/usr/include/glib-2.0/glib/gunicode.h \
		/usr/include/glib-2.0/glib/gutils.h \
		/usr/include/glib-2.0/glib/gkeyfile.h \
		/usr/include/glib-2.0/glib/gmappedfile.h \
		/usr/include/glib-2.0/glib/gmarkup.h \
		/usr/include/glib-2.0/glib/gmessages.h \
		/usr/include/glib-2.0/glib/goption.h \
		/usr/include/glib-2.0/glib/gpattern.h \
		/usr/include/glib-2.0/glib/gprimes.h \
		/usr/include/glib-2.0/glib/gqsort.h \
		/usr/include/glib-2.0/glib/gqueue.h \
		/usr/include/glib-2.0/glib/grand.h \
		/usr/include/glib-2.0/glib/gregex.h \
		/usr/include/glib-2.0/glib/gscanner.h \
		/usr/include/glib-2.0/glib/gsequence.h \
		/usr/include/glib-2.0/glib/gshell.h \
		/usr/include/glib-2.0/glib/gslice.h \
		/usr/include/glib-2.0/glib/gspawn.h \
		/usr/include/glib-2.0/glib/gstrfuncs.h \
		/usr/include/glib-2.0/glib/gstringchunk.h \
		/usr/include/glib-2.0/glib/gtestutils.h \
		/usr/include/glib-2.0/glib/gthreadpool.h \
		/usr/include/glib-2.0/glib/gtimer.h \
		/usr/include/glib-2.0/glib/gtrashstack.h \
		/usr/include/glib-2.0/glib/gtree.h \
		/usr/include/glib-2.0/glib/gurifuncs.h \
		/usr/include/glib-2.0/glib/gvarianttype.h \
		/usr/include/glib-2.0/glib/gvariant.h \
		/usr/include/glib-2.0/glib/gversion.h \
		/usr/include/glib-2.0/glib/gwin32.h \
		/usr/include/glib-2.0/glib/deprecated/gallocator.h \
		/usr/include/glib-2.0/glib/deprecated/gcache.h \
		/usr/include/glib-2.0/glib/deprecated/gcompletion.h \
		/usr/include/glib-2.0/glib/deprecated/gmain.h \
		/usr/include/glib-2.0/glib/deprecated/grel.h \
		/usr/include/glib-2.0/glib/deprecated/gthread.h \
		/usr/include/gstreamer-0.10/gst/glib-compat.h \
		/usr/include/gstreamer-0.10/gst/gstenumtypes.h \
		/usr/include/glib-2.0/glib-object.h \
		/usr/include/glib-2.0/gobject/gbinding.h \
		/usr/include/glib-2.0/gobject/gobject.h \
		/usr/include/glib-2.0/gobject/gtype.h \
		/usr/include/glib-2.0/gobject/gvalue.h \
		/usr/include/glib-2.0/gobject/gparam.h \
		/usr/include/glib-2.0/gobject/gclosure.h \
		/usr/include/glib-2.0/gobject/gsignal.h \
		/usr/include/glib-2.0/gobject/gmarshal.h \
		/usr/include/glib-2.0/gobject/gboxed.h \
		/usr/include/glib-2.0/gobject/glib-types.h \
		/usr/include/glib-2.0/gobject/genums.h \
		/usr/include/glib-2.0/gobject/gparamspecs.h \
		/usr/include/glib-2.0/gobject/gsourceclosure.h \
		/usr/include/glib-2.0/gobject/gtypemodule.h \
		/usr/include/glib-2.0/gobject/gtypeplugin.h \
		/usr/include/glib-2.0/gobject/gvaluearray.h \
		/usr/include/glib-2.0/gobject/gvaluetypes.h \
		/usr/include/gstreamer-0.10/gst/gstversion.h \
		/usr/include/gstreamer-0.10/gst/gstatomicqueue.h \
		/usr/include/gstreamer-0.10/gst/gstbin.h \
		/usr/include/gstreamer-0.10/gst/gstelement.h \
		/usr/include/gstreamer-0.10/gst/gstconfig.h \
		/usr/include/libxml2/libxml/parser.h \
		/usr/include/libxml2/libxml/xmlversion.h \
		/usr/include/libxml2/libxml/xmlexports.h \
		/usr/include/libxml2/libxml/tree.h \
		/usr/include/libxml2/libxml/xmlstring.h \
		/usr/include/libxml2/libxml/xmlregexp.h \
		/usr/include/libxml2/libxml/dict.h \
		/usr/include/libxml2/libxml/xmlmemory.h \
		/usr/include/libxml2/libxml/threads.h \
		/usr/include/libxml2/libxml/globals.h \
		/usr/include/libxml2/libxml/xmlerror.h \
		/usr/include/libxml2/libxml/SAX.h \
		/usr/include/libxml2/libxml/xlink.h \
		/usr/include/libxml2/libxml/SAX2.h \
		/usr/include/libxml2/libxml/hash.h \
		/usr/include/libxml2/libxml/valid.h \
		/usr/include/libxml2/libxml/list.h \
		/usr/include/libxml2/libxml/xmlautomata.h \
		/usr/include/libxml2/libxml/entities.h \
		/usr/include/libxml2/libxml/encoding.h \
		/usr/include/libxml2/libxml/xmlIO.h \
		/usr/include/gstreamer-0.10/gst/gstobject.h \
		/usr/include/gstreamer-0.10/gst/gstpad.h \
		/usr/include/gstreamer-0.10/gst/gstbuffer.h \
		/usr/include/gstreamer-0.10/gst/gstminiobject.h \
		/usr/include/gstreamer-0.10/gst/gstclock.h \
		/usr/include/gstreamer-0.10/gst/gstcaps.h \
		/usr/include/gstreamer-0.10/gst/gststructure.h \
		/usr/include/gstreamer-0.10/gst/gstdatetime.h \
		/usr/include/gstreamer-0.10/gst/gstbufferlist.h \
		/usr/include/gstreamer-0.10/gst/gstevent.h \
		/usr/include/gstreamer-0.10/gst/gstformat.h \
		/usr/include/gstreamer-0.10/gst/gstiterator.h \
		/usr/include/gstreamer-0.10/gst/gsttaglist.h \
		/usr/include/gstreamer-0.10/gst/gstquery.h \
		/usr/include/gstreamer-0.10/gst/gsttask.h \
		/usr/include/gstreamer-0.10/gst/gsttaskpool.h \
		/usr/include/gstreamer-0.10/gst/gstpadtemplate.h \
		/usr/include/gstreamer-0.10/gst/gstbus.h \
		/usr/include/gstreamer-0.10/gst/gstmessage.h \
		/usr/include/gstreamer-0.10/gst/gstelementfactory.h \
		/usr/include/gstreamer-0.10/gst/gstplugin.h \
		/usr/include/glib-2.0/gmodule.h \
		/usr/include/gstreamer-0.10/gst/gstmacros.h \
		/usr/include/gstreamer-0.10/gst/gstpluginfeature.h \
		/usr/include/gstreamer-0.10/gst/gstindex.h \
		/usr/include/gstreamer-0.10/gst/gstindexfactory.h \
		/usr/include/gstreamer-0.10/gst/gstchildproxy.h \
		/usr/include/gstreamer-0.10/gst/gstdebugutils.h \
		/usr/include/gstreamer-0.10/gst/gsterror.h \
		/usr/include/gstreamer-0.10/gst/gstghostpad.h \
		/usr/include/gstreamer-0.10/gst/gstinfo.h \
		/usr/include/gstreamer-0.10/gst/gstinterface.h \
		/usr/include/gstreamer-0.10/gst/gstmarshal.h \
		/usr/include/gstreamer-0.10/gst/gstparamspecs.h \
		/usr/include/gstreamer-0.10/gst/gstvalue.h \
		/usr/include/gstreamer-0.10/gst/gstpipeline.h \
		/usr/include/gstreamer-0.10/gst/gstpoll.h \
		/usr/include/gstreamer-0.10/gst/gstpreset.h \
		/usr/include/gstreamer-0.10/gst/gstregistry.h \
		/usr/include/gstreamer-0.10/gst/gstsegment.h \
		/usr/include/gstreamer-0.10/gst/gstsystemclock.h \
		/usr/include/gstreamer-0.10/gst/gsttagsetter.h \
		/usr/include/gstreamer-0.10/gst/gsttrace.h \
		/usr/include/gstreamer-0.10/gst/gsttypefind.h \
		/usr/include/gstreamer-0.10/gst/gsttypefindfactory.h \
		/usr/include/gstreamer-0.10/gst/gsturi.h \
		/usr/include/gstreamer-0.10/gst/gstutils.h \
		/usr/include/gstreamer-0.10/gst/gstparse.h \
		/usr/include/gstreamer-0.10/gst/gstxml.h \
		/usr/include/gstreamer-0.10/gst/gstcompat.h \
		gstreamerradio.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include gstreamerradio.h -o moc_gstreamerradio.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/usr/include/qt5/QtWidgets/QMainWindow \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtWidgets/QLabel \
		/usr/include/qt5/QtWidgets/qlabel.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtCore/QSettings \
		/usr/include/qt5/QtCore/qsettings.h \
		/usr/include/qt5/QtCore/QPropertyAnimation \
		/usr/include/qt5/QtCore/qpropertyanimation.h \
		/usr/include/qt5/QtCore/qvariantanimation.h \
		/usr/include/qt5/QtCore/qeasingcurve.h \
		/usr/include/qt5/QtCore/qabstractanimation.h \
		/usr/include/qt5/QtCore/QUrl \
		/usr/include/qt5/QtWidgets/QGraphicsOpacityEffect \
		/usr/include/qt5/QtWidgets/qgraphicseffect.h \
		/usr/include/qt5/QtGui/QDesktopServices \
		/usr/include/qt5/QtGui/qdesktopservices.h \
		/usr/include/qt5/QtCore/qstandardpaths.h \
		/usr/include/qt5/QtGui/QMouseEvent \
		/usr/include/qt5/QtWidgets/QApplication \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h \
		/usr/include/qt5/QtCore/QObject \
		currentsong.h \
		/usr/include/qt5/QtCore/QString \
		/usr/include/qt5/QtCore/QTimer \
		/usr/include/qt5/QtCore/qtimer.h \
		/usr/include/qt5/QtCore/qbasictimer.h \
		/usr/include/qt5/QtCore/QDebug \
		/usr/include/qt5/QtNetwork/QNetworkReply \
		/usr/include/qt5/QtNetwork/qnetworkreply.h \
		/usr/include/qt5/QtCore/QIODevice \
		/usr/include/qt5/QtCore/QVariant \
		/usr/include/qt5/QtNetwork/QNetworkRequest \
		/usr/include/qt5/QtNetwork/qnetworkrequest.h \
		/usr/include/qt5/QtCore/QSharedDataPointer \
		/usr/include/qt5/QtNetwork/QNetworkAccessManager \
		/usr/include/qt5/QtNetwork/qnetworkaccessmanager.h \
		/usr/include/qt5/QtNetwork/QSslConfiguration \
		/usr/include/qt5/QtNetwork/qsslconfiguration.h \
		/usr/include/qt5/QtNetwork/qsslsocket.h \
		/usr/include/qt5/QtNetwork/qtcpsocket.h \
		/usr/include/qt5/QtNetwork/qabstractsocket.h \
		/usr/include/qt5/QtNetwork/qsslerror.h \
		/usr/include/qt5/QtNetwork/qsslcertificate.h \
		/usr/include/qt5/QtCore/qcryptographichash.h \
		/usr/include/qt5/QtCore/qdatetime.h \
		/usr/include/qt5/QtNetwork/qssl.h \
		/usr/include/qt5/QtCore/QFlags \
		/usr/include/qt5/QtCore/QEventLoop \
		gstreamerradio.h \
		radio.h \
		/usr/include/gstreamer-0.10/gst/gst.h \
		/usr/include/glib-2.0/glib.h \
		/usr/include/glib-2.0/glib/galloca.h \
		/usr/include/glib-2.0/glib/gtypes.h \
		/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h \
		/usr/include/glib-2.0/glib/gmacros.h \
		/usr/include/glib-2.0/glib/gversionmacros.h \
		/usr/include/glib-2.0/glib/garray.h \
		/usr/include/glib-2.0/glib/gasyncqueue.h \
		/usr/include/glib-2.0/glib/gthread.h \
		/usr/include/glib-2.0/glib/gatomic.h \
		/usr/include/glib-2.0/glib/gerror.h \
		/usr/include/glib-2.0/glib/gquark.h \
		/usr/include/glib-2.0/glib/gbacktrace.h \
		/usr/include/glib-2.0/glib/gbase64.h \
		/usr/include/glib-2.0/glib/gbitlock.h \
		/usr/include/glib-2.0/glib/gbookmarkfile.h \
		/usr/include/glib-2.0/glib/gbytes.h \
		/usr/include/glib-2.0/glib/gcharset.h \
		/usr/include/glib-2.0/glib/gchecksum.h \
		/usr/include/glib-2.0/glib/gconvert.h \
		/usr/include/glib-2.0/glib/gdataset.h \
		/usr/include/glib-2.0/glib/gdate.h \
		/usr/include/glib-2.0/glib/gdatetime.h \
		/usr/include/glib-2.0/glib/gtimezone.h \
		/usr/include/glib-2.0/glib/gdir.h \
		/usr/include/glib-2.0/glib/genviron.h \
		/usr/include/glib-2.0/glib/gfileutils.h \
		/usr/include/glib-2.0/glib/ggettext.h \
		/usr/include/glib-2.0/glib/ghash.h \
		/usr/include/glib-2.0/glib/glist.h \
		/usr/include/glib-2.0/glib/gmem.h \
		/usr/include/glib-2.0/glib/gnode.h \
		/usr/include/glib-2.0/glib/ghmac.h \
		/usr/include/glib-2.0/glib/ghook.h \
		/usr/include/glib-2.0/glib/ghostutils.h \
		/usr/include/glib-2.0/glib/giochannel.h \
		/usr/include/glib-2.0/glib/gmain.h \
		/usr/include/glib-2.0/glib/gpoll.h \
		/usr/include/glib-2.0/glib/gslist.h \
		/usr/include/glib-2.0/glib/gstring.h \
		/usr/include/glib-2.0/glib/gunicode.h \
		/usr/include/glib-2.0/glib/gutils.h \
		/usr/include/glib-2.0/glib/gkeyfile.h \
		/usr/include/glib-2.0/glib/gmappedfile.h \
		/usr/include/glib-2.0/glib/gmarkup.h \
		/usr/include/glib-2.0/glib/gmessages.h \
		/usr/include/glib-2.0/glib/goption.h \
		/usr/include/glib-2.0/glib/gpattern.h \
		/usr/include/glib-2.0/glib/gprimes.h \
		/usr/include/glib-2.0/glib/gqsort.h \
		/usr/include/glib-2.0/glib/gqueue.h \
		/usr/include/glib-2.0/glib/grand.h \
		/usr/include/glib-2.0/glib/gregex.h \
		/usr/include/glib-2.0/glib/gscanner.h \
		/usr/include/glib-2.0/glib/gsequence.h \
		/usr/include/glib-2.0/glib/gshell.h \
		/usr/include/glib-2.0/glib/gslice.h \
		/usr/include/glib-2.0/glib/gspawn.h \
		/usr/include/glib-2.0/glib/gstrfuncs.h \
		/usr/include/glib-2.0/glib/gstringchunk.h \
		/usr/include/glib-2.0/glib/gtestutils.h \
		/usr/include/glib-2.0/glib/gthreadpool.h \
		/usr/include/glib-2.0/glib/gtimer.h \
		/usr/include/glib-2.0/glib/gtrashstack.h \
		/usr/include/glib-2.0/glib/gtree.h \
		/usr/include/glib-2.0/glib/gurifuncs.h \
		/usr/include/glib-2.0/glib/gvarianttype.h \
		/usr/include/glib-2.0/glib/gvariant.h \
		/usr/include/glib-2.0/glib/gversion.h \
		/usr/include/glib-2.0/glib/gwin32.h \
		/usr/include/glib-2.0/glib/deprecated/gallocator.h \
		/usr/include/glib-2.0/glib/deprecated/gcache.h \
		/usr/include/glib-2.0/glib/deprecated/gcompletion.h \
		/usr/include/glib-2.0/glib/deprecated/gmain.h \
		/usr/include/glib-2.0/glib/deprecated/grel.h \
		/usr/include/glib-2.0/glib/deprecated/gthread.h \
		/usr/include/gstreamer-0.10/gst/glib-compat.h \
		/usr/include/gstreamer-0.10/gst/gstenumtypes.h \
		/usr/include/glib-2.0/glib-object.h \
		/usr/include/glib-2.0/gobject/gbinding.h \
		/usr/include/glib-2.0/gobject/gobject.h \
		/usr/include/glib-2.0/gobject/gtype.h \
		/usr/include/glib-2.0/gobject/gvalue.h \
		/usr/include/glib-2.0/gobject/gparam.h \
		/usr/include/glib-2.0/gobject/gclosure.h \
		/usr/include/glib-2.0/gobject/gsignal.h \
		/usr/include/glib-2.0/gobject/gmarshal.h \
		/usr/include/glib-2.0/gobject/gboxed.h \
		/usr/include/glib-2.0/gobject/glib-types.h \
		/usr/include/glib-2.0/gobject/genums.h \
		/usr/include/glib-2.0/gobject/gparamspecs.h \
		/usr/include/glib-2.0/gobject/gsourceclosure.h \
		/usr/include/glib-2.0/gobject/gtypemodule.h \
		/usr/include/glib-2.0/gobject/gtypeplugin.h \
		/usr/include/glib-2.0/gobject/gvaluearray.h \
		/usr/include/glib-2.0/gobject/gvaluetypes.h \
		/usr/include/gstreamer-0.10/gst/gstversion.h \
		/usr/include/gstreamer-0.10/gst/gstatomicqueue.h \
		/usr/include/gstreamer-0.10/gst/gstbin.h \
		/usr/include/gstreamer-0.10/gst/gstelement.h \
		/usr/include/gstreamer-0.10/gst/gstconfig.h \
		/usr/include/libxml2/libxml/parser.h \
		/usr/include/libxml2/libxml/xmlversion.h \
		/usr/include/libxml2/libxml/xmlexports.h \
		/usr/include/libxml2/libxml/tree.h \
		/usr/include/libxml2/libxml/xmlstring.h \
		/usr/include/libxml2/libxml/xmlregexp.h \
		/usr/include/libxml2/libxml/dict.h \
		/usr/include/libxml2/libxml/xmlmemory.h \
		/usr/include/libxml2/libxml/threads.h \
		/usr/include/libxml2/libxml/globals.h \
		/usr/include/libxml2/libxml/xmlerror.h \
		/usr/include/libxml2/libxml/SAX.h \
		/usr/include/libxml2/libxml/xlink.h \
		/usr/include/libxml2/libxml/SAX2.h \
		/usr/include/libxml2/libxml/hash.h \
		/usr/include/libxml2/libxml/valid.h \
		/usr/include/libxml2/libxml/list.h \
		/usr/include/libxml2/libxml/xmlautomata.h \
		/usr/include/libxml2/libxml/entities.h \
		/usr/include/libxml2/libxml/encoding.h \
		/usr/include/libxml2/libxml/xmlIO.h \
		/usr/include/gstreamer-0.10/gst/gstobject.h \
		/usr/include/gstreamer-0.10/gst/gstpad.h \
		/usr/include/gstreamer-0.10/gst/gstbuffer.h \
		/usr/include/gstreamer-0.10/gst/gstminiobject.h \
		/usr/include/gstreamer-0.10/gst/gstclock.h \
		/usr/include/gstreamer-0.10/gst/gstcaps.h \
		/usr/include/gstreamer-0.10/gst/gststructure.h \
		/usr/include/gstreamer-0.10/gst/gstdatetime.h \
		/usr/include/gstreamer-0.10/gst/gstbufferlist.h \
		/usr/include/gstreamer-0.10/gst/gstevent.h \
		/usr/include/gstreamer-0.10/gst/gstformat.h \
		/usr/include/gstreamer-0.10/gst/gstiterator.h \
		/usr/include/gstreamer-0.10/gst/gsttaglist.h \
		/usr/include/gstreamer-0.10/gst/gstquery.h \
		/usr/include/gstreamer-0.10/gst/gsttask.h \
		/usr/include/gstreamer-0.10/gst/gsttaskpool.h \
		/usr/include/gstreamer-0.10/gst/gstpadtemplate.h \
		/usr/include/gstreamer-0.10/gst/gstbus.h \
		/usr/include/gstreamer-0.10/gst/gstmessage.h \
		/usr/include/gstreamer-0.10/gst/gstelementfactory.h \
		/usr/include/gstreamer-0.10/gst/gstplugin.h \
		/usr/include/glib-2.0/gmodule.h \
		/usr/include/gstreamer-0.10/gst/gstmacros.h \
		/usr/include/gstreamer-0.10/gst/gstpluginfeature.h \
		/usr/include/gstreamer-0.10/gst/gstindex.h \
		/usr/include/gstreamer-0.10/gst/gstindexfactory.h \
		/usr/include/gstreamer-0.10/gst/gstchildproxy.h \
		/usr/include/gstreamer-0.10/gst/gstdebugutils.h \
		/usr/include/gstreamer-0.10/gst/gsterror.h \
		/usr/include/gstreamer-0.10/gst/gstghostpad.h \
		/usr/include/gstreamer-0.10/gst/gstinfo.h \
		/usr/include/gstreamer-0.10/gst/gstinterface.h \
		/usr/include/gstreamer-0.10/gst/gstmarshal.h \
		/usr/include/gstreamer-0.10/gst/gstparamspecs.h \
		/usr/include/gstreamer-0.10/gst/gstvalue.h \
		/usr/include/gstreamer-0.10/gst/gstpipeline.h \
		/usr/include/gstreamer-0.10/gst/gstpoll.h \
		/usr/include/gstreamer-0.10/gst/gstpreset.h \
		/usr/include/gstreamer-0.10/gst/gstregistry.h \
		/usr/include/gstreamer-0.10/gst/gstsegment.h \
		/usr/include/gstreamer-0.10/gst/gstsystemclock.h \
		/usr/include/gstreamer-0.10/gst/gsttagsetter.h \
		/usr/include/gstreamer-0.10/gst/gsttrace.h \
		/usr/include/gstreamer-0.10/gst/gsttypefind.h \
		/usr/include/gstreamer-0.10/gst/gsttypefindfactory.h \
		/usr/include/gstreamer-0.10/gst/gsturi.h \
		/usr/include/gstreamer-0.10/gst/gstutils.h \
		/usr/include/gstreamer-0.10/gst/gstparse.h \
		/usr/include/gstreamer-0.10/gst/gstxml.h \
		/usr/include/gstreamer-0.10/gst/gstcompat.h \
		/usr/include/qt5/QtWidgets/QDesktopWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/include/qt5/QtWidgets/QMainWindow \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtWidgets/QLabel \
		/usr/include/qt5/QtWidgets/qlabel.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtCore/QSettings \
		/usr/include/qt5/QtCore/qsettings.h \
		/usr/include/qt5/QtCore/QPropertyAnimation \
		/usr/include/qt5/QtCore/qpropertyanimation.h \
		/usr/include/qt5/QtCore/qvariantanimation.h \
		/usr/include/qt5/QtCore/qeasingcurve.h \
		/usr/include/qt5/QtCore/qabstractanimation.h \
		/usr/include/qt5/QtCore/QUrl \
		/usr/include/qt5/QtWidgets/QGraphicsOpacityEffect \
		/usr/include/qt5/QtWidgets/qgraphicseffect.h \
		/usr/include/qt5/QtGui/QDesktopServices \
		/usr/include/qt5/QtGui/qdesktopservices.h \
		/usr/include/qt5/QtCore/qstandardpaths.h \
		/usr/include/qt5/QtGui/QMouseEvent \
		/usr/include/qt5/QtWidgets/QApplication \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h \
		/usr/include/qt5/QtCore/QObject \
		currentsong.h \
		/usr/include/qt5/QtCore/QString \
		/usr/include/qt5/QtCore/QTimer \
		/usr/include/qt5/QtCore/qtimer.h \
		/usr/include/qt5/QtCore/qbasictimer.h \
		/usr/include/qt5/QtCore/QDebug \
		/usr/include/qt5/QtNetwork/QNetworkReply \
		/usr/include/qt5/QtNetwork/qnetworkreply.h \
		/usr/include/qt5/QtCore/QIODevice \
		/usr/include/qt5/QtCore/QVariant \
		/usr/include/qt5/QtNetwork/QNetworkRequest \
		/usr/include/qt5/QtNetwork/qnetworkrequest.h \
		/usr/include/qt5/QtCore/QSharedDataPointer \
		/usr/include/qt5/QtNetwork/QNetworkAccessManager \
		/usr/include/qt5/QtNetwork/qnetworkaccessmanager.h \
		/usr/include/qt5/QtNetwork/QSslConfiguration \
		/usr/include/qt5/QtNetwork/qsslconfiguration.h \
		/usr/include/qt5/QtNetwork/qsslsocket.h \
		/usr/include/qt5/QtNetwork/qtcpsocket.h \
		/usr/include/qt5/QtNetwork/qabstractsocket.h \
		/usr/include/qt5/QtNetwork/qsslerror.h \
		/usr/include/qt5/QtNetwork/qsslcertificate.h \
		/usr/include/qt5/QtCore/qcryptographichash.h \
		/usr/include/qt5/QtCore/qdatetime.h \
		/usr/include/qt5/QtNetwork/qssl.h \
		/usr/include/qt5/QtCore/QFlags \
		/usr/include/qt5/QtCore/QEventLoop \
		gstreamerradio.h \
		radio.h \
		/usr/include/gstreamer-0.10/gst/gst.h \
		/usr/include/glib-2.0/glib.h \
		/usr/include/glib-2.0/glib/galloca.h \
		/usr/include/glib-2.0/glib/gtypes.h \
		/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h \
		/usr/include/glib-2.0/glib/gmacros.h \
		/usr/include/glib-2.0/glib/gversionmacros.h \
		/usr/include/glib-2.0/glib/garray.h \
		/usr/include/glib-2.0/glib/gasyncqueue.h \
		/usr/include/glib-2.0/glib/gthread.h \
		/usr/include/glib-2.0/glib/gatomic.h \
		/usr/include/glib-2.0/glib/gerror.h \
		/usr/include/glib-2.0/glib/gquark.h \
		/usr/include/glib-2.0/glib/gbacktrace.h \
		/usr/include/glib-2.0/glib/gbase64.h \
		/usr/include/glib-2.0/glib/gbitlock.h \
		/usr/include/glib-2.0/glib/gbookmarkfile.h \
		/usr/include/glib-2.0/glib/gbytes.h \
		/usr/include/glib-2.0/glib/gcharset.h \
		/usr/include/glib-2.0/glib/gchecksum.h \
		/usr/include/glib-2.0/glib/gconvert.h \
		/usr/include/glib-2.0/glib/gdataset.h \
		/usr/include/glib-2.0/glib/gdate.h \
		/usr/include/glib-2.0/glib/gdatetime.h \
		/usr/include/glib-2.0/glib/gtimezone.h \
		/usr/include/glib-2.0/glib/gdir.h \
		/usr/include/glib-2.0/glib/genviron.h \
		/usr/include/glib-2.0/glib/gfileutils.h \
		/usr/include/glib-2.0/glib/ggettext.h \
		/usr/include/glib-2.0/glib/ghash.h \
		/usr/include/glib-2.0/glib/glist.h \
		/usr/include/glib-2.0/glib/gmem.h \
		/usr/include/glib-2.0/glib/gnode.h \
		/usr/include/glib-2.0/glib/ghmac.h \
		/usr/include/glib-2.0/glib/ghook.h \
		/usr/include/glib-2.0/glib/ghostutils.h \
		/usr/include/glib-2.0/glib/giochannel.h \
		/usr/include/glib-2.0/glib/gmain.h \
		/usr/include/glib-2.0/glib/gpoll.h \
		/usr/include/glib-2.0/glib/gslist.h \
		/usr/include/glib-2.0/glib/gstring.h \
		/usr/include/glib-2.0/glib/gunicode.h \
		/usr/include/glib-2.0/glib/gutils.h \
		/usr/include/glib-2.0/glib/gkeyfile.h \
		/usr/include/glib-2.0/glib/gmappedfile.h \
		/usr/include/glib-2.0/glib/gmarkup.h \
		/usr/include/glib-2.0/glib/gmessages.h \
		/usr/include/glib-2.0/glib/goption.h \
		/usr/include/glib-2.0/glib/gpattern.h \
		/usr/include/glib-2.0/glib/gprimes.h \
		/usr/include/glib-2.0/glib/gqsort.h \
		/usr/include/glib-2.0/glib/gqueue.h \
		/usr/include/glib-2.0/glib/grand.h \
		/usr/include/glib-2.0/glib/gregex.h \
		/usr/include/glib-2.0/glib/gscanner.h \
		/usr/include/glib-2.0/glib/gsequence.h \
		/usr/include/glib-2.0/glib/gshell.h \
		/usr/include/glib-2.0/glib/gslice.h \
		/usr/include/glib-2.0/glib/gspawn.h \
		/usr/include/glib-2.0/glib/gstrfuncs.h \
		/usr/include/glib-2.0/glib/gstringchunk.h \
		/usr/include/glib-2.0/glib/gtestutils.h \
		/usr/include/glib-2.0/glib/gthreadpool.h \
		/usr/include/glib-2.0/glib/gtimer.h \
		/usr/include/glib-2.0/glib/gtrashstack.h \
		/usr/include/glib-2.0/glib/gtree.h \
		/usr/include/glib-2.0/glib/gurifuncs.h \
		/usr/include/glib-2.0/glib/gvarianttype.h \
		/usr/include/glib-2.0/glib/gvariant.h \
		/usr/include/glib-2.0/glib/gversion.h \
		/usr/include/glib-2.0/glib/gwin32.h \
		/usr/include/glib-2.0/glib/deprecated/gallocator.h \
		/usr/include/glib-2.0/glib/deprecated/gcache.h \
		/usr/include/glib-2.0/glib/deprecated/gcompletion.h \
		/usr/include/glib-2.0/glib/deprecated/gmain.h \
		/usr/include/glib-2.0/glib/deprecated/grel.h \
		/usr/include/glib-2.0/glib/deprecated/gthread.h \
		/usr/include/gstreamer-0.10/gst/glib-compat.h \
		/usr/include/gstreamer-0.10/gst/gstenumtypes.h \
		/usr/include/glib-2.0/glib-object.h \
		/usr/include/glib-2.0/gobject/gbinding.h \
		/usr/include/glib-2.0/gobject/gobject.h \
		/usr/include/glib-2.0/gobject/gtype.h \
		/usr/include/glib-2.0/gobject/gvalue.h \
		/usr/include/glib-2.0/gobject/gparam.h \
		/usr/include/glib-2.0/gobject/gclosure.h \
		/usr/include/glib-2.0/gobject/gsignal.h \
		/usr/include/glib-2.0/gobject/gmarshal.h \
		/usr/include/glib-2.0/gobject/gboxed.h \
		/usr/include/glib-2.0/gobject/glib-types.h \
		/usr/include/glib-2.0/gobject/genums.h \
		/usr/include/glib-2.0/gobject/gparamspecs.h \
		/usr/include/glib-2.0/gobject/gsourceclosure.h \
		/usr/include/glib-2.0/gobject/gtypemodule.h \
		/usr/include/glib-2.0/gobject/gtypeplugin.h \
		/usr/include/glib-2.0/gobject/gvaluearray.h \
		/usr/include/glib-2.0/gobject/gvaluetypes.h \
		/usr/include/gstreamer-0.10/gst/gstversion.h \
		/usr/include/gstreamer-0.10/gst/gstatomicqueue.h \
		/usr/include/gstreamer-0.10/gst/gstbin.h \
		/usr/include/gstreamer-0.10/gst/gstelement.h \
		/usr/include/gstreamer-0.10/gst/gstconfig.h \
		/usr/include/libxml2/libxml/parser.h \
		/usr/include/libxml2/libxml/xmlversion.h \
		/usr/include/libxml2/libxml/xmlexports.h \
		/usr/include/libxml2/libxml/tree.h \
		/usr/include/libxml2/libxml/xmlstring.h \
		/usr/include/libxml2/libxml/xmlregexp.h \
		/usr/include/libxml2/libxml/dict.h \
		/usr/include/libxml2/libxml/xmlmemory.h \
		/usr/include/libxml2/libxml/threads.h \
		/usr/include/libxml2/libxml/globals.h \
		/usr/include/libxml2/libxml/xmlerror.h \
		/usr/include/libxml2/libxml/SAX.h \
		/usr/include/libxml2/libxml/xlink.h \
		/usr/include/libxml2/libxml/SAX2.h \
		/usr/include/libxml2/libxml/hash.h \
		/usr/include/libxml2/libxml/valid.h \
		/usr/include/libxml2/libxml/list.h \
		/usr/include/libxml2/libxml/xmlautomata.h \
		/usr/include/libxml2/libxml/entities.h \
		/usr/include/libxml2/libxml/encoding.h \
		/usr/include/libxml2/libxml/xmlIO.h \
		/usr/include/gstreamer-0.10/gst/gstobject.h \
		/usr/include/gstreamer-0.10/gst/gstpad.h \
		/usr/include/gstreamer-0.10/gst/gstbuffer.h \
		/usr/include/gstreamer-0.10/gst/gstminiobject.h \
		/usr/include/gstreamer-0.10/gst/gstclock.h \
		/usr/include/gstreamer-0.10/gst/gstcaps.h \
		/usr/include/gstreamer-0.10/gst/gststructure.h \
		/usr/include/gstreamer-0.10/gst/gstdatetime.h \
		/usr/include/gstreamer-0.10/gst/gstbufferlist.h \
		/usr/include/gstreamer-0.10/gst/gstevent.h \
		/usr/include/gstreamer-0.10/gst/gstformat.h \
		/usr/include/gstreamer-0.10/gst/gstiterator.h \
		/usr/include/gstreamer-0.10/gst/gsttaglist.h \
		/usr/include/gstreamer-0.10/gst/gstquery.h \
		/usr/include/gstreamer-0.10/gst/gsttask.h \
		/usr/include/gstreamer-0.10/gst/gsttaskpool.h \
		/usr/include/gstreamer-0.10/gst/gstpadtemplate.h \
		/usr/include/gstreamer-0.10/gst/gstbus.h \
		/usr/include/gstreamer-0.10/gst/gstmessage.h \
		/usr/include/gstreamer-0.10/gst/gstelementfactory.h \
		/usr/include/gstreamer-0.10/gst/gstplugin.h \
		/usr/include/glib-2.0/gmodule.h \
		/usr/include/gstreamer-0.10/gst/gstmacros.h \
		/usr/include/gstreamer-0.10/gst/gstpluginfeature.h \
		/usr/include/gstreamer-0.10/gst/gstindex.h \
		/usr/include/gstreamer-0.10/gst/gstindexfactory.h \
		/usr/include/gstreamer-0.10/gst/gstchildproxy.h \
		/usr/include/gstreamer-0.10/gst/gstdebugutils.h \
		/usr/include/gstreamer-0.10/gst/gsterror.h \
		/usr/include/gstreamer-0.10/gst/gstghostpad.h \
		/usr/include/gstreamer-0.10/gst/gstinfo.h \
		/usr/include/gstreamer-0.10/gst/gstinterface.h \
		/usr/include/gstreamer-0.10/gst/gstmarshal.h \
		/usr/include/gstreamer-0.10/gst/gstparamspecs.h \
		/usr/include/gstreamer-0.10/gst/gstvalue.h \
		/usr/include/gstreamer-0.10/gst/gstpipeline.h \
		/usr/include/gstreamer-0.10/gst/gstpoll.h \
		/usr/include/gstreamer-0.10/gst/gstpreset.h \
		/usr/include/gstreamer-0.10/gst/gstregistry.h \
		/usr/include/gstreamer-0.10/gst/gstsegment.h \
		/usr/include/gstreamer-0.10/gst/gstsystemclock.h \
		/usr/include/gstreamer-0.10/gst/gsttagsetter.h \
		/usr/include/gstreamer-0.10/gst/gsttrace.h \
		/usr/include/gstreamer-0.10/gst/gsttypefind.h \
		/usr/include/gstreamer-0.10/gst/gsttypefindfactory.h \
		/usr/include/gstreamer-0.10/gst/gsturi.h \
		/usr/include/gstreamer-0.10/gst/gstutils.h \
		/usr/include/gstreamer-0.10/gst/gstparse.h \
		/usr/include/gstreamer-0.10/gst/gstxml.h \
		/usr/include/gstreamer-0.10/gst/gstcompat.h \
		ui_mainwindow.h \
		/usr/include/qt5/QtWidgets/QAction \
		/usr/include/qt5/QtWidgets/qaction.h \
		/usr/include/qt5/QtWidgets/qactiongroup.h \
		/usr/include/qt5/QtWidgets/QButtonGroup \
		/usr/include/qt5/QtWidgets/qbuttongroup.h \
		/usr/include/qt5/QtWidgets/QCheckBox \
		/usr/include/qt5/QtWidgets/qcheckbox.h \
		/usr/include/qt5/QtWidgets/qabstractbutton.h \
		/usr/include/qt5/QtWidgets/QHeaderView \
		/usr/include/qt5/QtWidgets/qheaderview.h \
		/usr/include/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/qt5/QtWidgets/qstyleoption.h \
		/usr/include/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/qt5/QtGui/qvalidator.h \
		/usr/include/qt5/QtCore/qregularexpression.h \
		/usr/include/qt5/QtWidgets/qslider.h \
		/usr/include/qt5/QtWidgets/qabstractslider.h \
		/usr/include/qt5/QtWidgets/qstyle.h \
		/usr/include/qt5/QtWidgets/qtabbar.h \
		/usr/include/qt5/QtWidgets/qrubberband.h \
		/usr/include/qt5/QtWidgets/QPushButton \
		/usr/include/qt5/QtWidgets/qpushbutton.h \
		/usr/include/qt5/QtWidgets/QSlider \
		/usr/include/qt5/QtWidgets/QToolButton \
		/usr/include/qt5/QtWidgets/qtoolbutton.h \
		/usr/include/qt5/QtWidgets/QWidget \
		efects.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

currentsong.o: currentsong.cpp currentsong.h \
		/usr/include/qt5/QtCore/QString \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/QUrl \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtCore/QTimer \
		/usr/include/qt5/QtCore/qtimer.h \
		/usr/include/qt5/QtCore/qbasictimer.h \
		/usr/include/qt5/QtCore/QDebug \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtNetwork/QNetworkReply \
		/usr/include/qt5/QtNetwork/qnetworkreply.h \
		/usr/include/qt5/QtCore/QIODevice \
		/usr/include/qt5/QtCore/QVariant \
		/usr/include/qt5/QtNetwork/QNetworkRequest \
		/usr/include/qt5/QtNetwork/qnetworkrequest.h \
		/usr/include/qt5/QtCore/QSharedDataPointer \
		/usr/include/qt5/QtNetwork/QNetworkAccessManager \
		/usr/include/qt5/QtNetwork/qnetworkaccessmanager.h \
		/usr/include/qt5/QtCore/QObject \
		/usr/include/qt5/QtNetwork/QSslConfiguration \
		/usr/include/qt5/QtNetwork/qsslconfiguration.h \
		/usr/include/qt5/QtNetwork/qsslsocket.h \
		/usr/include/qt5/QtNetwork/qtcpsocket.h \
		/usr/include/qt5/QtNetwork/qabstractsocket.h \
		/usr/include/qt5/QtNetwork/qsslerror.h \
		/usr/include/qt5/QtNetwork/qsslcertificate.h \
		/usr/include/qt5/QtCore/qcryptographichash.h \
		/usr/include/qt5/QtCore/qdatetime.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtNetwork/qssl.h \
		/usr/include/qt5/QtCore/QFlags \
		/usr/include/qt5/QtCore/QEventLoop \
		/usr/include/qt5/QtCore/qeventloop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o currentsong.o currentsong.cpp

gstreamerradio.o: gstreamerradio.cpp gstreamerradio.h \
		/usr/include/qt5/QtCore/QDebug \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		radio.h \
		/usr/include/qt5/QtCore/QObject \
		/usr/include/qt5/QtCore/QString \
		/usr/include/gstreamer-0.10/gst/gst.h \
		/usr/include/glib-2.0/glib.h \
		/usr/include/glib-2.0/glib/galloca.h \
		/usr/include/glib-2.0/glib/gtypes.h \
		/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h \
		/usr/include/glib-2.0/glib/gmacros.h \
		/usr/include/glib-2.0/glib/gversionmacros.h \
		/usr/include/glib-2.0/glib/garray.h \
		/usr/include/glib-2.0/glib/gasyncqueue.h \
		/usr/include/glib-2.0/glib/gthread.h \
		/usr/include/glib-2.0/glib/gatomic.h \
		/usr/include/glib-2.0/glib/gerror.h \
		/usr/include/glib-2.0/glib/gquark.h \
		/usr/include/glib-2.0/glib/gbacktrace.h \
		/usr/include/glib-2.0/glib/gbase64.h \
		/usr/include/glib-2.0/glib/gbitlock.h \
		/usr/include/glib-2.0/glib/gbookmarkfile.h \
		/usr/include/glib-2.0/glib/gbytes.h \
		/usr/include/glib-2.0/glib/gcharset.h \
		/usr/include/glib-2.0/glib/gchecksum.h \
		/usr/include/glib-2.0/glib/gconvert.h \
		/usr/include/glib-2.0/glib/gdataset.h \
		/usr/include/glib-2.0/glib/gdate.h \
		/usr/include/glib-2.0/glib/gdatetime.h \
		/usr/include/glib-2.0/glib/gtimezone.h \
		/usr/include/glib-2.0/glib/gdir.h \
		/usr/include/glib-2.0/glib/genviron.h \
		/usr/include/glib-2.0/glib/gfileutils.h \
		/usr/include/glib-2.0/glib/ggettext.h \
		/usr/include/glib-2.0/glib/ghash.h \
		/usr/include/glib-2.0/glib/glist.h \
		/usr/include/glib-2.0/glib/gmem.h \
		/usr/include/glib-2.0/glib/gnode.h \
		/usr/include/glib-2.0/glib/ghmac.h \
		/usr/include/glib-2.0/glib/ghook.h \
		/usr/include/glib-2.0/glib/ghostutils.h \
		/usr/include/glib-2.0/glib/giochannel.h \
		/usr/include/glib-2.0/glib/gmain.h \
		/usr/include/glib-2.0/glib/gpoll.h \
		/usr/include/glib-2.0/glib/gslist.h \
		/usr/include/glib-2.0/glib/gstring.h \
		/usr/include/glib-2.0/glib/gunicode.h \
		/usr/include/glib-2.0/glib/gutils.h \
		/usr/include/glib-2.0/glib/gkeyfile.h \
		/usr/include/glib-2.0/glib/gmappedfile.h \
		/usr/include/glib-2.0/glib/gmarkup.h \
		/usr/include/glib-2.0/glib/gmessages.h \
		/usr/include/glib-2.0/glib/goption.h \
		/usr/include/glib-2.0/glib/gpattern.h \
		/usr/include/glib-2.0/glib/gprimes.h \
		/usr/include/glib-2.0/glib/gqsort.h \
		/usr/include/glib-2.0/glib/gqueue.h \
		/usr/include/glib-2.0/glib/grand.h \
		/usr/include/glib-2.0/glib/gregex.h \
		/usr/include/glib-2.0/glib/gscanner.h \
		/usr/include/glib-2.0/glib/gsequence.h \
		/usr/include/glib-2.0/glib/gshell.h \
		/usr/include/glib-2.0/glib/gslice.h \
		/usr/include/glib-2.0/glib/gspawn.h \
		/usr/include/glib-2.0/glib/gstrfuncs.h \
		/usr/include/glib-2.0/glib/gstringchunk.h \
		/usr/include/glib-2.0/glib/gtestutils.h \
		/usr/include/glib-2.0/glib/gthreadpool.h \
		/usr/include/glib-2.0/glib/gtimer.h \
		/usr/include/glib-2.0/glib/gtrashstack.h \
		/usr/include/glib-2.0/glib/gtree.h \
		/usr/include/glib-2.0/glib/gurifuncs.h \
		/usr/include/glib-2.0/glib/gvarianttype.h \
		/usr/include/glib-2.0/glib/gvariant.h \
		/usr/include/glib-2.0/glib/gversion.h \
		/usr/include/glib-2.0/glib/gwin32.h \
		/usr/include/glib-2.0/glib/deprecated/gallocator.h \
		/usr/include/glib-2.0/glib/deprecated/gcache.h \
		/usr/include/glib-2.0/glib/deprecated/gcompletion.h \
		/usr/include/glib-2.0/glib/deprecated/gmain.h \
		/usr/include/glib-2.0/glib/deprecated/grel.h \
		/usr/include/glib-2.0/glib/deprecated/gthread.h \
		/usr/include/gstreamer-0.10/gst/glib-compat.h \
		/usr/include/gstreamer-0.10/gst/gstenumtypes.h \
		/usr/include/glib-2.0/glib-object.h \
		/usr/include/glib-2.0/gobject/gbinding.h \
		/usr/include/glib-2.0/gobject/gobject.h \
		/usr/include/glib-2.0/gobject/gtype.h \
		/usr/include/glib-2.0/gobject/gvalue.h \
		/usr/include/glib-2.0/gobject/gparam.h \
		/usr/include/glib-2.0/gobject/gclosure.h \
		/usr/include/glib-2.0/gobject/gsignal.h \
		/usr/include/glib-2.0/gobject/gmarshal.h \
		/usr/include/glib-2.0/gobject/gboxed.h \
		/usr/include/glib-2.0/gobject/glib-types.h \
		/usr/include/glib-2.0/gobject/genums.h \
		/usr/include/glib-2.0/gobject/gparamspecs.h \
		/usr/include/glib-2.0/gobject/gsourceclosure.h \
		/usr/include/glib-2.0/gobject/gtypemodule.h \
		/usr/include/glib-2.0/gobject/gtypeplugin.h \
		/usr/include/glib-2.0/gobject/gvaluearray.h \
		/usr/include/glib-2.0/gobject/gvaluetypes.h \
		/usr/include/gstreamer-0.10/gst/gstversion.h \
		/usr/include/gstreamer-0.10/gst/gstatomicqueue.h \
		/usr/include/gstreamer-0.10/gst/gstbin.h \
		/usr/include/gstreamer-0.10/gst/gstelement.h \
		/usr/include/gstreamer-0.10/gst/gstconfig.h \
		/usr/include/libxml2/libxml/parser.h \
		/usr/include/libxml2/libxml/xmlversion.h \
		/usr/include/libxml2/libxml/xmlexports.h \
		/usr/include/libxml2/libxml/tree.h \
		/usr/include/libxml2/libxml/xmlstring.h \
		/usr/include/libxml2/libxml/xmlregexp.h \
		/usr/include/libxml2/libxml/dict.h \
		/usr/include/libxml2/libxml/xmlmemory.h \
		/usr/include/libxml2/libxml/threads.h \
		/usr/include/libxml2/libxml/globals.h \
		/usr/include/libxml2/libxml/xmlerror.h \
		/usr/include/libxml2/libxml/SAX.h \
		/usr/include/libxml2/libxml/xlink.h \
		/usr/include/libxml2/libxml/SAX2.h \
		/usr/include/libxml2/libxml/hash.h \
		/usr/include/libxml2/libxml/valid.h \
		/usr/include/libxml2/libxml/list.h \
		/usr/include/libxml2/libxml/xmlautomata.h \
		/usr/include/libxml2/libxml/entities.h \
		/usr/include/libxml2/libxml/encoding.h \
		/usr/include/libxml2/libxml/xmlIO.h \
		/usr/include/gstreamer-0.10/gst/gstobject.h \
		/usr/include/gstreamer-0.10/gst/gstpad.h \
		/usr/include/gstreamer-0.10/gst/gstbuffer.h \
		/usr/include/gstreamer-0.10/gst/gstminiobject.h \
		/usr/include/gstreamer-0.10/gst/gstclock.h \
		/usr/include/gstreamer-0.10/gst/gstcaps.h \
		/usr/include/gstreamer-0.10/gst/gststructure.h \
		/usr/include/gstreamer-0.10/gst/gstdatetime.h \
		/usr/include/gstreamer-0.10/gst/gstbufferlist.h \
		/usr/include/gstreamer-0.10/gst/gstevent.h \
		/usr/include/gstreamer-0.10/gst/gstformat.h \
		/usr/include/gstreamer-0.10/gst/gstiterator.h \
		/usr/include/gstreamer-0.10/gst/gsttaglist.h \
		/usr/include/gstreamer-0.10/gst/gstquery.h \
		/usr/include/gstreamer-0.10/gst/gsttask.h \
		/usr/include/gstreamer-0.10/gst/gsttaskpool.h \
		/usr/include/gstreamer-0.10/gst/gstpadtemplate.h \
		/usr/include/gstreamer-0.10/gst/gstbus.h \
		/usr/include/gstreamer-0.10/gst/gstmessage.h \
		/usr/include/gstreamer-0.10/gst/gstelementfactory.h \
		/usr/include/gstreamer-0.10/gst/gstplugin.h \
		/usr/include/glib-2.0/gmodule.h \
		/usr/include/gstreamer-0.10/gst/gstmacros.h \
		/usr/include/gstreamer-0.10/gst/gstpluginfeature.h \
		/usr/include/gstreamer-0.10/gst/gstindex.h \
		/usr/include/gstreamer-0.10/gst/gstindexfactory.h \
		/usr/include/gstreamer-0.10/gst/gstchildproxy.h \
		/usr/include/gstreamer-0.10/gst/gstdebugutils.h \
		/usr/include/gstreamer-0.10/gst/gsterror.h \
		/usr/include/gstreamer-0.10/gst/gstghostpad.h \
		/usr/include/gstreamer-0.10/gst/gstinfo.h \
		/usr/include/gstreamer-0.10/gst/gstinterface.h \
		/usr/include/gstreamer-0.10/gst/gstmarshal.h \
		/usr/include/gstreamer-0.10/gst/gstparamspecs.h \
		/usr/include/gstreamer-0.10/gst/gstvalue.h \
		/usr/include/gstreamer-0.10/gst/gstpipeline.h \
		/usr/include/gstreamer-0.10/gst/gstpoll.h \
		/usr/include/gstreamer-0.10/gst/gstpreset.h \
		/usr/include/gstreamer-0.10/gst/gstregistry.h \
		/usr/include/gstreamer-0.10/gst/gstsegment.h \
		/usr/include/gstreamer-0.10/gst/gstsystemclock.h \
		/usr/include/gstreamer-0.10/gst/gsttagsetter.h \
		/usr/include/gstreamer-0.10/gst/gsttrace.h \
		/usr/include/gstreamer-0.10/gst/gsttypefind.h \
		/usr/include/gstreamer-0.10/gst/gsttypefindfactory.h \
		/usr/include/gstreamer-0.10/gst/gsturi.h \
		/usr/include/gstreamer-0.10/gst/gstutils.h \
		/usr/include/gstreamer-0.10/gst/gstparse.h \
		/usr/include/gstreamer-0.10/gst/gstxml.h \
		/usr/include/gstreamer-0.10/gst/gstcompat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gstreamerradio.o gstreamerradio.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_currentsong.o: moc_currentsong.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_currentsong.o moc_currentsong.cpp

moc_radio.o: moc_radio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_radio.o moc_radio.cpp

moc_gstreamerradio.o: moc_gstreamerradio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gstreamerradio.o moc_gstreamerradio.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

